on:
  push:
    branches:
      - staging
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.carissaso.ca
        username: flggit@flg.carissaso.ca
        password: ${{ secrets.ftp_password }}
        exclude: |
            **/.git*
            **/.git*/**
            README.md
            **/desk/**
